CREATE TABLE CATEGORIA(
IdCategoria NVARCHAR2(10),
Nombre      NVARCHAR2(20) NOT NULL,
PRIMARY KEY(IdCategoria)
);
SELECT * FROM CATEGORIA;

CREATE TABLE MARCA(
IdMarca     NVARCHAR2(10),
Nombre      NVARCHAR2(20) NOT NULL,
Fecha       DATE NOT NULL,
Email       NVARCHAR2(30) UNIQUE,
PRIMARY KEY(IdMarca)
);
SELECT*FROM MARCA;

CREATE TABLE SEGMENTACION(
IdSegmentacion     NVARCHAR2(10),
Nombre             NVARCHAR2(20) NOT NULL,
Beneficio          NVARCHAR2(30) NOT NULL,
PRIMARY KEY(IdSegmentacion)
);
SELECT*FROM SEGMENTACION;

CREATE TABLE ADMINISTRADOR(
IdAdministrador    VARCHAR2(13),
Nombre             NVARCHAR2(30) NOT NULL,
Apellido           NVARCHAR2(30) NOT NULL,
PRIMARY KEY(IdAdministrador)
);
SELECT*FROM ADMINISTRADOR;

CREATE TABLE MOTORISTA(
IdMotorista        VARCHAR2(13),
Nombre             NVARCHAR2(30) NOT NULL,
Apellido           NVARCHAR2(30) NOT NULL,
TipoTransporte     NVARCHAR2(30) NOT NULL,
Placa              VARCHAR2(8),
PRIMARY KEY(IdMotorista)
);
SELECT*FROM MOTORISTA;

CREATE TABLE ENCARGADO_INVENTARIO(
IdEncargado        VARCHAR2(13),
Nombre             NVARCHAR2(30) NOT NULL,
Apellido           NVARCHAR2(30) NOT NULL,
PRIMARY KEY(IdEncargado)
);
SELECT*FROM ENCARGADO_INVENTARIO;